manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyr-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nxp
      url-base: https://github.com/NXP
    - name: nxp-zsdk
      url-base: https://github.com/nxp-zephyr

  defaults:
    remote: zephyr-rtos

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyr-rtos
      revision: v4.2.0
      import:
        name-allowlist:
          - zephyr 
          - mbedtls
          - cmsis
          - cmsis_6
          - segger
          - hal_nordic
          - hal_espressif
          - hal_rpi_pico
          - hal_nxp

    - name: els_pkc
      remote: nxp
      repo-path: els_pkc
      revision: 71d4a89c03fb32e618ee02c0cd54b3fc92736c96
      path: modules/crypto/els_pkc
      groups:
        - crypto
